# Generated by Django 2.2 on 2019-10-18 04:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import earth_trash.trash.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garbage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='type name')),
                ('photo', models.ImageField(upload_to=earth_trash.trash.models.generate_filename)),
            ],
            options={
                'db_table': 'garbage',
            },
        ),
        migrations.CreateModel(
            name='GarbageOfTrashRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'garbage_of_trash_record',
            },
        ),
        migrations.CreateModel(
            name='TrashRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discoverer', models.CharField(max_length=100, verbose_name='Trash discoverer')),
                ('dtime', models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 18, 4, 13, 9, 464302), null=True, verbose_name='Trash discover time')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=7, verbose_name='Trash latitude')),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Trash longitude')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note something')),
            ],
            options={
                'db_table': 'trash_record',
            },
        ),
        migrations.AddIndex(
            model_name='trashrecord',
            index=models.Index(fields=['dtime'], name='trash_recor_dtime_b30e23_idx'),
        ),
        migrations.AddField(
            model_name='garbageoftrashrecord',
            name='garbage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='trash.Garbage', verbose_name='trash record'),
        ),
        migrations.AddField(
            model_name='garbageoftrashrecord',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garbage_types', to='trash.TrashRecord', verbose_name='garbage types'),
        ),
        migrations.AddIndex(
            model_name='garbage',
            index=models.Index(fields=['name'], name='garbage_name_9dbd7f_idx'),
        ),
    ]
