# Generated by Django 2.2 on 2019-10-18 16:30

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garbageoftrashrecord',
            name='origin',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='The place of origin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trashrecord',
            name='dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 18, 16, 29, 56, 952277), null=True, verbose_name='Trash discover time'),
        ),
    ]
