# Generated by Django 2.2 on 2019-10-18 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='type name'),
        ),
        migrations.AlterField(
            model_name='trashrecord',
            name='dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 18, 4, 22, 22, 386638), null=True, verbose_name='Trash discover time'),
        ),
    ]
