# Generated by Django 2.2 on 2019-10-19 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garbageoftrashrecord',
            name='origin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='The place of origin'),
        ),
        migrations.AlterField(
            model_name='trashrecord',
            name='dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 19, 8, 10, 38, 360492), null=True, verbose_name='Trash discover time'),
        ),
    ]
