# Generated by Django 2.2 on 2019-10-19 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0004_auto_20191019_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashrecord',
            name='dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 19, 13, 32, 30, 77624), null=True, verbose_name='Trash discover time'),
        ),
    ]
