# Generated by Django 2.2 on 2019-10-19 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash', '0005_auto_20191019_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashrecord',
            name='location',
            field=models.CharField(max_length=100, null=True, verbose_name='Discover location'),
        ),
        migrations.AlterField(
            model_name='trashrecord',
            name='dtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 19, 17, 44, 26, 849794), null=True, verbose_name='Trash discover time'),
        ),
    ]
